sudo: required

language: node

services:
  - docker

branches:
  only:
  - master
  - develop
  - staging
  - QA

jobs:
  include:
    - stage: Dbetl-Backend-Flowz
      script:
      - 'if [ ${TRAVIS_BRANCH} = "master" ]; then
            docker login -u="$DOCKER_USERNAME_FLOWZ" -p="$DOCKER_PASSWORD_FLOWZ";
            docker build -t dbetl_backend_flowz:latest --build-arg domainkey="$DOMAINKEY_MASTER" ./service/;
            docker images;
            docker tag dbetl_backend_flowz:latest $DOCKER_USERNAME_FLOWZ/dbetl_backend_flowz:latest;
            docker push $DOCKER_USERNAME_FLOWZ/dbetl_backend_flowz:latest;
        elif [ ${TRAVIS_BRANCH} = "develop" ]; then
            docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
            docker build -t dbetl_backend_flowz:dev --build-arg domainkey="$DOMAINKEY_DEVELOP" ./service/;
            docker images;
            docker tag dbetl_backend_flowz:dev $DOCKER_USERNAME/dbetl_backend_flowz:dev;
            docker push $DOCKER_USERNAME/dbetl_backend_flowz:dev;
        elif [ ${TRAVIS_BRANCH} = "staging" ]; then
            docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
            docker build -t dbetl_backend_flowz:$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER --build-arg domainkey="$DOMAINKEY_STAGING" ./service/;
            docker tag dbetl_backend_flowz:$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER $DOCKER_USERNAME/dbetl_backend_flowz:$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER;
            docker tag dbetl_backend_flowz:$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER $DOCKER_USERNAME/dbetl_backend_flowz:staging;
            docker images;
            docker push $DOCKER_USERNAME/dbetl_backend_flowz:s$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER;
            docker push $DOCKER_USERNAME/dbetl_backend_flowz:staging;
        else
            docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
            docker build -t dbetl_backend_flowz:qa --build-arg domainkey="$DOMAINKEY_QA" ./service/;
            docker images;
            docker tag dbetl_backend_flowz:qa $DOCKER_USERNAME/dbetl_backend_flowz:qa;
            docker push $DOCKER_USERNAME/dbetl_backend_flowz:qa;
        fi'
    - stage: Dbetl-Frontend-Flowz
      script:
      - 'if [ ${TRAVIS_BRANCH} = "master" ]; then
            docker login -u="$DOCKER_USERNAME_FLOWZ" -p="$DOCKER_PASSWORD_FLOWZ";
            docker build -t dbetl_frontend_flowz:latest --build-arg accesskey="$AWS_ACCESSKEY" --build-arg secretkey="AWS_SECRETKEY" --build-arg domainkey="$DOMAINKEY_MASTER" ./client/;
            docker images;
            docker tag dbetl_frontend_flowz:latest $DOCKER_USERNAME_FLOWZ/dbetl_frontend_flowz:latest;
            docker push $DOCKER_USERNAME_FLOWZ/dbetl_frontend_flowz:latest;
        elif [ ${TRAVIS_BRANCH} = "develop" ]; then
            docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
            docker build -t dbetl_frontend_flowz:dev --build-arg accesskey="$AWS_ACCESSKEY" --build-arg secretkey="AWS_SECRETKEY" --build-arg domainkey="$DOMAINKEY_DEVELOP" ./client/;
            docker images;
            docker tag dbetl_frontend_flowz:dev $DOCKER_USERNAME/dbetl_frontend_flowz:dev;
            docker push $DOCKER_USERNAME/dbetl_frontend_flowz:dev;
        elif [ ${TRAVIS_BRANCH} = "staging" ]; then
            docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
            docker build -t dbetl_frontend_flowz:$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER --build-arg accesskey="$AWS_ACCESSKEY" --build-arg secretkey="AWS_SECRETKEY" --build-arg domainkey="$DOMAINKEY_STAGING" ./client/;
            docker tag dbetl_frontend_flowz:$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER $DOCKER_USERNAME/dbetl_frontend_flowz:$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER;
            docker tag dbetl_frontend_flowz:$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER $DOCKER_USERNAME/dbetl_frontend_flowz:staging;
            docker images;
            docker push $DOCKER_USERNAME/dbetl_frontend_flowz:$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER;
            docker push $DOCKER_USERNAME/dbetl_frontend_flowz:staging;
        else
            docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
            docker build -t dbetl_frontend_flowz:qa --build-arg accesskey="$AWS_ACCESSKEY" --build-arg secretkey="AWS_SECRETKEY" --build-arg domainkey="$DOMAINKEY_QA" ./client/;
            docker images;
            docker tag dbetl_frontend_flowz:qa $DOCKER_USERNAME/dbetl_frontend_flowz:qa;
            docker push $DOCKER_USERNAME/dbetl_frontend_flowz:qa;
        fi'
    - stage: Upgrade Rancher Service
      script:
      - bash ./upgrade.sh
    - stage: Finish Rancher Service
      script:
      - bash ./finish.sh

notifications:
  email:
    recipients:
      - arpitap@officebeacon.com
      - kaushalm@officebrain.com
      - anuj@officebrain.com
      - naveeng@officebrain.com
      - rbajaniya@officebrain.com
    on_success: always
    on_failure: always
